### PR TITLE
Wip/update

### PR DESCRIPTION
**Pull request by Mehrad0711**
Cleanup pipeline names, update image and repo versions, and add all active pipelines to `upload_all_pipelines.sh`

### CODE REVIEW

**Review by gcampax — COMMENTED** [review]
This changes all the names of the pipelines, which will result in a lot of obsolete pipelines and a lot of confusion. Is it worth doing?

**Comment by Mehrad0711** [comment]
Yeah but there were already inconsistencies between the pipeline name and the published name such as https://github.com/stanford-oval/genie-k8s/blob/d436809ae52727446ca822ae545acb9d31e627bf/upload_all_pipelines.sh#L11
There are only 4 pipelines affected which we usually don't use individually except for train_eval so it shouldn't affect other people. I will remove old pipelines and publish the new ones.

**Comment by gcampax** [comment]
I use the eval-only pipeline a lot, not sure how you define "which we usually don't use"...

**Comment by Mehrad0711** [comment]
I just want the naming to be consistent. If you prefer keeping "only" for single-step pipelines, then I just fix bootleg and train_eval_only and revert the rest.

**Comment by gcampax** [comment]
I don't mind us being consistent with new pipeline names. But we were not consistent before, and I think fixing the pipeline names just for consistency now is not worth the pain.

**Pull request merged**
